### ISSUE TITLE
Incorrect output message with unexpected parameters

### ISSUE THREAD

**Issue by cervonwong** [NUSH-MA2/MAAD-2020#3]
When entering any clue number not within the intended bounds, the output message is: 

"Your next clue is Clue -1"

This should not happen as there is no Clue with the index -1.

===

When entering 0 for one or both of the longitude and latitude fields, it shows that I have completed the quiz.

![image](https://user-images.githubusercontent.com/44718681/93743126-07e8b400-fc22-11ea-83bb-1712feb5a2e6.png)

This should not happen. 

![image](https://user-images.githubusercontent.com/44718681/93743190-25b61900-fc22-11ea-8e4d-7193d7fdf8f6.png)

**Comment by NUSH-MA2** [comment]
Hi Cervon, 
This is an intended outcome of the redirection tool, as the final coordinates were still graded manually for the endpoint that each mentor group reaches.
