### ISSUE TITLE
You are a good coder

### ISSUE THREAD

**Issue by Raindrops69Whee** [NUSH-MA2/MAAD-2020#5]
Just put coords for null island to get endpoint lmao

**Comment by cervonwong** [comment]
_The favoured term is "developer" or "programmer"!_

**Comment by Raindrops69Whee** [comment]
Thank you cervon. I would also like to state the absence of meaningful variable names, as x, y, x1, y1, x2 and y2 are not meaningful variable names. The absence of comments are also disturbing.

**Comment by cervonwong** [comment]
It is imperative that every line of code is commented! Someone should work on a PR to fix that pronto!!

**Comment by NUSH-MA2** [comment]
Hi Cervon and Raindrops,

> Just put coords for null island to get endpoint lmao

This is a feature, not a bug. The intention of the player should be to find the right coordinates as these are checked separately.
